application: perfjs
version: 1-7-bench
runtime: java
public_root: /static
#default_expiration: "15d"
#sessions_enabled: true

static_files:
  - exclude: tests/*

resource_files:
  - exclude: README.md
  - exclude: package.json

handlers:
  - url: /*
    servlet: org.ringojs.jsgi.JsgiServlet
    name: ringo
    init_params:  
      module-path: src
      config: main
      app: app 
      optlevel: -1
      ringo-home: /
